config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :games


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :hands
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :hands
  has_many :players, through: :hands
end

app/models/hand.rb
class Hand < ApplicationRecord
  belongs_to :game
  belongs_to :player
  belongs_to :card
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :hands
  has_many :games, through: :hands
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def show
    @game = Game.find(params[:id])
    @hands = @game.hands
  end

  def index
    @games = Game.all
  end

  def new
    
  end

  
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/games/index.html.erb
<%= link_to "Create a Game", new_game_path%>

<h3> Join a Public Game </h3>
<% @games.each do |game| %>
  <%= link_to "Game ##{game.id}", game_path(game) %>
<% end %>


<h3> Join a Private Game </h3>

app/views/games/show.html.erb
<h1>Welcome to Game <%=@game.id %>!</h1> 

Players:
<ul>
  <% @hands.each do |hand| %>
    <li><%= link_to hand.player.username, player_path(hand.player) %> </li>
  <% end %>
</ul>


Cards:
<ul>
  <% @hands.each do |hand| %>
    <li><%= link_to hand.card.name, card_path(hand.card) %> </li>
  <% end %>
</ul>

app/views/home/index.html.erb
<h1>Welcome to Werewolf!!!</h1>

<%= link_to "View the Games!", games_path %>

app/views/home/info.html.erb
<p>This app was created by Kristin Donovan, Michael Handwerker, Alex Martin, JJ Seymour, Alex Siega, and Dean Watts. It's *kind* of a big deal.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Court</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>